<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta http-equiv="cache-control" content="no-cache">
<meta http-equiv="pragma" content="no-cache">
<style type="text/css">
    table {
        border-collapse: collapse;
        background: #99CCFF;
        border: 2px solid black;
    }
    th {
        padding: 5px;
        background: #E6E6FA;
        border: 1px solid black;
    }
    td {
        padding: 4px;
        background: #FDF5E6;
        border: 1px solid black;
        white-space:nowrap;
    }

    .t_table {
        border-collapse: collapse;
        background: #99CCFF;
        border: 2px solid black;
    }
    
    .t_table tr:hover td {
        border-collapse: collapse;
        background: #e0ffff;
    }
  
   
   .success {
      color: black;
      background-color: #00FF00;
   }
   .warning {
      color: black;
      background-color: #FFFF00;
   }
   .error {
      color: black;
      background-color: #FF0000;
   }
   .fault {
      color: #990000;
      background-color: #FFFFCC;
      font-weight: bold;
   }
   .monosp {
      font-family: monospace;
   }
</style>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js">
  /*
    all web pages with Google Charts should include the following lines in the <head> of the web page:
    https://developers.google.com/chart/interactive/docs/basic_load_libs
    :::: ACHTUNG ::::
    do NOT put these lines into each chart js-block, otherwise runtime exception occurs:
    "too much recursion" (Firefox) or "Maximum call stack size exceeds" (Chrome)
    See: https://groups.google.com/forum/#!topic/Google-Visualization-Api/iigCT7a-MFk
  */
</script>
<script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
</script>

</head>
